name: bluetooth_low_energy_darwin
description: "iOS and macOS implementation of the bluetooth_low_energy plugin with lazy BLE initialization."
version: 6.0.0
homepage: https://github.com/yanshouwang/bluetooth_low_energy
repository: https://github.com/yanshouwang/bluetooth_low_energy
issue_tracker: https://github.com/yanshouwang/bluetooth_low_energy/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BluetoothLowEnergyBitchatPlugin
        sharedDarwinSource: true
        dartPluginClass: BluetoothLowEnergyBitchatPlugin
      macos:
        pluginClass: BluetoothLowEnergyBitchatPlugin
        sharedDarwinSource: true
        dartPluginClass: BluetoothLowEnergyBitchatPlugin
